In [1]:
import time
lista = list(range(10000000))
inicio = time.time()
[valor * 2 for valor in lista]
print("tiempo con lista", time.time() - inicio)

tiempo con lista 1.1959247589111328


In [2]:
import numpy as np
array = np.arange(10000000)
inicio = time.time()
array * 2
print("tiempo con mumpy", time.time() - inicio)

tiempo con mumpy 0.04237842559814453


In [3]:
!pip install numpy

In [ ]:
import numpy as np


In [6]:
arreglo = np.array([1,2,3,4], dtype=int)
print(arreglo)

[1 2 3 4]


In [9]:
print("numero de dimenciones del arreglo",arreglo.ndim)

numero de dimenciones del arreglo 1


In [15]:
arreglo2d = np.array([[1,2,3,4],[5,9,8,10]])
print(arreglo1)

[[ 1  2  3  4]
 [ 5  9  8 10]]


In [11]:
print("forma del arreglo",arreglo.shape)

forma del arreglo (4,)


In [14]:
print("el total de elemntos en el arreglo:",arreglo.size)
print("tipo de datos del arreglo",arreglo.dtype)

el total de elemntos en el arreglo: 4
tipo de datos del arreglo int64


In [16]:
print("el total de elemntos en el arreglo:",arreglo2d.size)
print("tipo de datos del arreglo",arreglo2d.dtype)
print("forma del arreglo",arreglo2d.shape)

el total de elemntos en el arreglo: 8
tipo de datos del arreglo int64
forma del arreglo (2, 4)


In [20]:
arreglo3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arreglo3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
print("numero de dimenciones del arreglo",arreglo3d.ndim)
print("el total de elemntos en el arreglo:",arreglo3d.size)
print("tipo de datos del arreglo",arreglo3d.dtype)
print("forma del arreglo",arreglo3d.shape)

numero de dimenciones del arreglo 3
el total de elemntos en el arreglo: 12
tipo de datos del arreglo int64
forma del arreglo (2, 2, 3)


In [25]:
ceros = np.zeros((2,3))
ceros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
matriz = np.empty((3,3))
matriz

array([[4.83075756e-315, 0.00000000e+000, 3.68205014e+180],
       [1.96083001e+243, 1.96567591e-062, 3.44996707e-085],
       [5.66774924e+160, 1.28625507e+248, 1.02765654e-321]])

In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [33]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [36]:
np.random.rand(2,3)

array([[0.66399145, 0.43492885, 0.68669105],
       [0.00348643, 0.57050586, 0.69095441]])

In [37]:
arreglo1 = np.array([[1,0],[-1,1]])
arreglo1/0

/tmp/ipykernel_12643/1979197916.py:2: RuntimeWarning: divide by zero encountered in divide
  arreglo1/0
/tmp/ipykernel_12643/1979197916.py:2: RuntimeWarning: invalid value encountered in divide
  arreglo1/0


array([[ inf,  nan],
       [-inf,  inf]])

In [39]:
arreglo2 = np.array([[np.inf,np.nan],[1,2]])
arreglo2

array([[inf, nan],
       [ 1.,  2.]])

In [44]:
array_inf = np.array([1,2.5])**1000
print(array_inf)

[ 1. inf]


/tmp/ipykernel_12643/2988506827.py:1: RuntimeWarning: overflow encountered in power
  array_inf = np.array([1,2.5])**1000
