In [ ]:
import numpy as np

In [ ]:
brigadas = np.array([[["juan", "antonio", "ricardo"],["alonso", "jorge", "salvador"]],
                    [["david","julian","ricardo"],["arturo","ramiro","esteban"]],
                    [["arturo","ricardo","lucio"],["jorge","marco","juan"]],
                    [["alonso","julian","salvador"],["ricardo","jorge","esteban"]],
                    [["arturo","ricardo","lucio"],["jorge","marco","juan"]]])

In [ ]:
brigadas.ndim

3

In [ ]:
brigadas.shape

(5, 2, 3)

In [ ]:
brigadas[1:3]

array([[['david', 'julian', 'ricardo'],
        ['arturo', 'ramiro', 'esteban']],

       [['arturo', 'ricardo', 'lucio'],
        ['jorge', 'marco', 'juan']]], dtype='<U8')

In [ ]:
brigadas[1:3,:,:]

array([[['david', 'julian', 'ricardo'],
        ['arturo', 'ramiro', 'esteban']],

       [['arturo', 'ricardo', 'lucio'],
        ['jorge', 'marco', 'juan']]], dtype='<U8')

In [ ]:
brigadas[1:3,:,:].shape

(2, 2, 3)

In [ ]:
brigadas[1:3,1,:]

array([['arturo', 'ramiro', 'esteban'],
       ['jorge', 'marco', 'juan']], dtype='<U8')

In [ ]:
brigadas[1:3,1,:].shape

(2, 3)

In [ ]:
brigadas[:,1,0:2]

array([['alonso', 'jorge'],
       ['arturo', 'ramiro'],
       ['jorge', 'marco'],
       ['ricardo', 'jorge'],
       ['jorge', 'marco']], dtype='<U8')

In [ ]:
brigadas[:,1,0:2].shape

(5, 2)

In [ ]:
sustitutos = np.array([["john","ringo","paul"],["keith","mick","charlie"]])

In [ ]:
sustitutos.shape

(2, 3)

In [ ]:
brigadas[4,:,:] = sustitutos

In [ ]:
print(brigadas)

[[['juan' 'antonio' 'ricardo']
  ['alonso' 'jorge' 'salvador']]

 [['david' 'julian' 'ricardo']
  ['arturo' 'ramiro' 'esteban']]

 [['arturo' 'ricardo' 'lucio']
  ['jorge' 'marco' 'juan']]

 [['alonso' 'julian' 'salvador']
  ['ricardo' 'jorge' 'esteban']]

 [['john' 'ringo' 'paul']
  ['keith' 'mick' 'charlie']]]


In [ ]:
brigadas[1,1,:]= ["parcibal","gwain","lancelot"]

In [ ]:
brigadas

array([[['juan', 'antonio', 'ricardo'],
        ['alonso', 'jorge', 'salvador']],

       [['david', 'julian', 'ricardo'],
        ['parcibal', 'gwain', 'lancelot']],

       [['arturo', 'ricardo', 'lucio'],
        ['jorge', 'marco', 'juan']],

       [['alonso', 'julian', 'salvador'],
        ['ricardo', 'jorge', 'esteban']],

       [['john', 'ringo', 'paul'],
        ['keith', 'mick', 'charlie']]], dtype='<U8')

In [ ]:
brigadas[2,0,0:2] = ["salomon","sanson"]

In [ ]:
brigadas[4,1,2]= "pascual"

In [ ]:
print(brigadas)

[[['juan' 'antonio' 'ricardo']
  ['alonso' 'jorge' 'salvador']]

 [['david' 'julian' 'ricardo']
  ['parcibal' 'gwain' 'lancelot']]

 [['arturo' 'ricardo' 'lucio']
  ['jorge' 'marco' 'juan']]

 [['alonso' 'julian' 'salvador']
  ['ricardo' 'jorge' 'esteban']]

 [['john' 'ringo' 'paul']
  ['keith' 'mick' 'pascual']]]


# OPERACIONES NUMERICAS

In [ ]:
matriz_1 = np.array([[1,2,3],[4,0,5],[-6,-7,-8]])

In [ ]:
matriz_1 + 100

array([[101, 102, 103],
       [104, 100, 105],
       [ 94,  93,  92]])

In [ ]:
matriz_1[2,:]*3

array([-18, -21, -24])

In [ ]:
3 / matriz_1

/tmp/ipykernel_23942/113740686.py:1: RuntimeWarning: divide by zero encountered in divide
  3 / matriz_1


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf,  0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [ ]:
matriz_1 /2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  0. ,  2.5],
       [-3. , -3.5, -4. ]])

In [ ]:
matriz_1 > 1

array([[False,  True,  True],
       [ True, False,  True],
       [False, False, False]])

In [ ]:
matriz_2 = np.array([1,2,3])

In [ ]:
matriz_2.shape

(3,)

In [ ]:
matriz_1 * matriz_2

array([[  1,   4,   9],
       [  4,   0,  15],
       [ -6, -14, -24]])

se multiplica por cada fila 1 con 1, 2 con 2, 3 con 3

In [ ]:
matriz_3 = np.array([[2],[4],[6]])

In [ ]:
matriz_3.shape

(3, 1)

In [ ]:
matriz_3*matriz_1

array([[  2,   4,   6],
       [ 16,   0,  20],
       [-36, -42, -48]])

In [ ]:
np.array([[1,2,3],[4,0,5],[-6,-7,-8]])

In [ ]:
#funcion numpy reshape

In [ ]:
arreglo_2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
arreglo_2.shape

(3, 4)

In [ ]:
arreglo_2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arreglo_3 = np.array([[1,2],[3,4]])

In [ ]:
arreglo_3.shape

(2, 2)

In [ ]:
arreglo_3.resize(3,3,2)

In [ ]:
arreglo_3

array([[[1, 2],
        [3, 4],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
arreglo_2.resize(3,5,5)

In [ ]:
arreglo_2

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]])

In [ ]:
#transponer matriz

In [ ]:
matriz_1.transpose

In [ ]:
origen = np.arange(9).reshape(3,3,1)

In [ ]:
origen

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [ ]:
np.squeeze(origen, 2)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#unir arreglos np.concatenate

In [ ]:
arreglo_1 =np.array([[1,2],[3,4]])

In [ ]:
arreglo_2 =np.array([[5,6],[7,8]])

In [ ]:
np.concatenate((arreglo_1,arreglo_2), axis =1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((arreglo_1,arreglo_2),0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#eje 1 columnas, eje 0 filas

In [ ]:
np.append() #unir, se debe especificar el eje

In [ ]:
arreglo_eje_1 = np.arange(7,13).reshape(3,2)